### ISSUE TITLE
Why spectre?

### ISSUE THREAD

**Issue by kidder** [BlackHolePerturbationToolkit/GremlinEq#1]
It's going to be really confusing to have multiple public GR codes named spectre...
https://github.com/sxs-collaboration/spectre

**Comment by nielsw2** [comment]
This is the initial public release of Scott Hughes' Teukolsky code which for some years has been internally called Spectre. We agree this will cause confusion with the new SPeC code. For that reason we have renamed the code to Gremlin (the name the original code had many years ago).

**Comment by kidder** [comment]
Okay, thank you! I think this will save us both some confusion.  Good luck with your public release.
